# Site settings
title: Einfach-Luxus
author: Simon Greuter
domain: greuters.github.io
email:
github_username: greuters

lang: de
baseurl: ""
url: https://greuters.github.io
rss: rss-feed
disqus:
  shortname:

# ordered list of top level pages that should be prominently shown in navigation
prominent_top_level_urls:
  - /gwunderwelt/
  - /nordkapp-solar/

liquid:
  error_mode: strict
  strict_filters: true
  # strict_variables can unfortunately not be enabled due to feed.xml generation
  # strict_variables: true

emptyArray: []

# Settings for polyglot
languages: ["de", "en", "es", "fr"]
default_lang: "de"
# TODO: get images working without localizing them
# exclude_from_localization: ["assets/css", "assets/images"]
exclude_from_localization: ["assets/css"]
parallel_localization: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-polyglot
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
