# Site settings
title: Einfach-Luxus
author: Simon Greuter
domain: greuters.github.io
email:
github_username: greuters

lang: de
baseurl: ""
url: https://greuters.github.io
description: Simple-Luxury. My personal blog about possible comfort in a sustainable world, sufficiency and other interesting stuff.
rss: rss-feed
disqus:
  shortname:

# ordered list of top level pages that should be prominently shown in navigation
prominent_top_level_urls:
  - /gwunderwelt/
  - /nordkapp-solar/

liquid:
  error_mode: strict
  strict_filters: true
  # strict_variables can unfortunately not be enabled due to feed.xml generation
  # strict_variables: true

emptyArray: []

# Settings for polyglot
languages: ["de", "en", "es", "fr"]
default_lang: "de"
# Explicitly not excluding assets/images from localization to be able to statically verify they are available in load-images.liquid
# See polyglot bug https://github.com/untra/polyglot/issues/131
# -> static files are not available for sub-language pages when they are excluded from localization
# to avoid having multiple copies of all images around, they are replaced with symbolic links after build, see package.json postbuild script
exclude_from_localization: ["assets/dist"]
parallel_localization: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-polyglot

# TODO: enable - jekyll-paginate

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - Makefile
  - original_icons
  - package.json
  - package-lock.json
