title: Luxe-Simple
site_description: |
  Simplicité. Confort.
  Comment construire un monde qui offre notre luxe à tous, sans détruire la planète ?
lang_name: Français
date_format: "%-d/%m/%Y"
read_full_post: Lire tout l'article..
recent_posts: Articles actuels
rss_subscribe: '<a href="$url">abonner par RSS</a>'
no_translation: Désolé, cette page n'est pas disponible en français.
closeGallery: Fermer la galerie
toggleMaximize: Maximiser
previousSlide: Photo précédente
nextSlide: Photo suivante
download: Télécharger
playVideo: Lancer la vidéo
mediaLoadingFailed: Oups... Échec du chargement du contenu...
