title: Einfach-Luxus
lang_name: Français
date_format: "%-d/%m/%Y"
read_full_post: Lire tout l'article..
recent_posts: TODO Aktuelle Beiträge
rss_subscribe: '<a href="$url">abonner par RSS</a>'
no_translation: Désolé, cette page n'est pas disponible en français.
