title: "Einfach-Luxus"
lang_name: "Français"
read_full_post: "Lire tout l'article.."
rss_subscribe: '<a href="$url">abonner par RSS</a>'
no_translation: "Désolé, cette page n'est pas disponible en français."