title: Einfach-Luxus
lang_name: Español
read_full_post: Leer el artículo completo..
date_format: "%-d/%b/%Y"
rss_subscribe: '<a href="$url">suscríbase por RSS</a>'
no_translation: Lo siento, esta página no está disponible en español.
