title: "Einfach-Luxus"
lang_name: "Deutsch"
read_full_post: "Den ganzen Beitrag lesen.."
rss_subscribe: '<a href="$url">per RSS abonnieren</a>'
no_translation: "Tut mir leid, dieser Seite ist auf Deutsch nicht verfügbar."