title: Einfach-Luxus
site_description: |
  Einfachheit. Komfort.
  Wie erreichen wir eine Welt in der unser Luxus für alle möglich ist, ohne die Umwelt zu zerstören?
lang_name: Deutsch
# TODO: l10n of month names and use following format
# date_format: "%-d. %B %Y"
date_format: "%-d.%-m.%Y"
recent_posts: Aktuelle Beiträge
read_full_post: Den ganzen Beitrag lesen..
rss_subscribe: '<a href="$url">per RSS abonnieren</a>'
no_translation: Tut mir leid, diese Seite ist auf Deutsch nicht verfügbar.
closeGallery: "Galerie schliessen"
toggleMaximize: "Maximieren"
previousSlide: "Vorheriges Foto"
nextSlide: "Nächstes Foto"
download: "Download"
playVideo: "Video abspielen"
mediaLoadingFailed: "Ups... Ladevorgang fehlgeschlagen..."
