title: Einfach-Luxus
lang_name: English
date_format: "%-d/%b/%Y"
read_full_post: Read the full post..
rss_subscribe: '<a href="$url">subscribe via RSS</a>'
no_translation: Sorry, this page is not available in English.
